Ext.define(Dnet.ns.tx + "Stock_Ds$Trl", {
	available__lbl: "Disponibil",
	inventoryId__lbl: "Gestiune(ID)",
	inventoryName__lbl: "Gestiune(Den)",
	inventory__lbl: "Gestiune",
	locatorId__lbl: "Locaţie(ID)",
	locatorName__lbl: "Locaţie(Den)",
	locator__lbl: "Locaţie",
	orgId__lbl: "Organizaţie(ID)",
	org__lbl: "Organizaţie",
	productId__lbl: "Articol(ID)",
	productName__lbl: "Articol(Den)",
	product__lbl: "Articol",
	quantity__lbl: "Cantitate",
	reserved__lbl: "Rezervat",
	uomId__lbl: "UM(ID)",
	uom__lbl: "UM",
	valueLoc__lbl: "",
	valueRef__lbl: ""
});
