Ext.define(Dnet.ns.sd + "PaymentInAmount_Ds$Trl", {
	amountDue__lbl: "Due/Remained",
	amountId__lbl: "Amount Owed(ID)",
	amountInitial__lbl: "Due/Initial",
	amountInitial__lbl_From: "Due/Initial(From)",
	amountInitial__lbl_To: "Due/Initial(To)",
	amountPayed__lbl: "Due/Payed",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	currentPayment__lbl: "Used amount",
	customerAccountId__lbl: "Customer account(ID)",
	customerId__lbl: "Customer(ID)",
	customerName__lbl: "Customer(Name)",
	customer__lbl: "Customer",
	invoiceDocDate__lbl: "Invoice date",
	invoiceId__lbl: "Sales Invoice(ID)",
	invoice__lbl: "Invoice",
	paymentAmount__lbl: "Payed amount",
	paymentDate__lbl: "Payment date",
	paymentDocNo__lbl: "Payment doc",
	paymentId__lbl: "Payment(ID)",
	paymentSourceDocNo__lbl: "Payment src doc"
});
