Ext.define(Dnet.ns.sd + "PaymentInAmountProposal_Ds$Trl", {
	amountDue__lbl: "Due amount",
	amountDue__lbl_From: "Due amount(From)",
	amountDue__lbl_To: "Due amount(To)",
	amountInitial__lbl: "Initial amount",
	amountInitial__lbl_From: "Initial amount(From)",
	amountInitial__lbl_To: "Initial amount(To)",
	amountPayed__lbl: "Payed amount",
	bpAccountId__lbl: "Bp Account(ID)",
	businessPartnerName__lbl: "Received from(Name)",
	businessPartner__lbl: "Received from",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	currentPayment__lbl: "Current payment",
	dueDate__lbl: "Due Date",
	dueDate__lbl_From: "Due Date(From)",
	dueDate__lbl_To: "Due Date(To)",
	paymentCurrency__lbl: "Currency",
	paymentId__lbl: "",
	receivedAmount__lbl: "Received amount",
	remainingAmount__lbl: "Remaining",
	unAllocatedAmount__lbl: "Unused amount"
});
