Ext.define(Dnet.ns.sd + "PaymentIn_Ds$Trl", {
	amountLoc__lbl: "Amount Loc",
	amountRef__lbl: "Amount Ref",
	amount__lbl: "Amount",
	bpAccountId__lbl: "Bp Account(ID)",
	bpartnerId__lbl: "Business partner(ID)",
	bpartnerName__lbl: "Business partner(Name)",
	bpartner__lbl: "Business partner",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	confirmed__lbl: "Confirmed",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	docDate__lbl: "Doc Date",
	docDate__lbl_From: "Doc Date(From)",
	docDate__lbl_To: "Doc Date(To)",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	generated__lbl: "Generated",
	posted__lbl: "Posted",
	sourceDocNo__lbl: "Source Doc No",
	xrateLoc__lbl: "Exchange rate [L]",
	xrateRef__lbl: "Exchange rate [R]"
});
