Ext.define(Dnet.ns.sd + "Receivable_Ds$Trl", {
	amountPayed__lbl: "Amount Payed",
	amountPayed__lbl_From: "Amount Payed(From)",
	amountPayed__lbl_To: "Amount Payed(To)",
	amountRemained__lbl: "Amount Remained",
	amountRemained__lbl_From: "Amount Remained(From)",
	amountRemained__lbl_To: "Amount Remained(To)",
	amount__lbl: "Amount",
	amount__lbl_From: "Amount(From)",
	amount__lbl_To: "Amount(To)",
	bpAccountId__lbl: "Bp Account(ID)",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerId__lbl: "Business partner(ID)",
	customerName__lbl: "Business partner(Name)",
	customer__lbl: "Business partner",
	dueDate__lbl: "Due Date",
	dueDate__lbl_From: "Due Date(From)",
	dueDate__lbl_To: "Due Date(To)",
	dueInDays__lbl: "Due In Days",
	invoiceDate__lbl: "Doc Date",
	invoiceId__lbl: "Sales Invoice(ID)",
	invoiceNo__lbl: "Doc No"
});
