Ext.define(Dnet.ns.sd + "Receivable_Ds$Trl", {
	amountDue__lbl: "Due amount",
	amountDue__lbl_From: "Due amount(From)",
	amountDue__lbl_To: "Due amount(To)",
	amountInitial__lbl: "Initial amount",
	amountInitial__lbl_From: "Initial amount(From)",
	amountInitial__lbl_To: "Initial amount(To)",
	amountPayed__lbl: "Payed amount",
	amountPayed__lbl_From: "Payed amount(From)",
	amountPayed__lbl_To: "Payed amount(To)",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerAccountId__lbl: "Customer account(ID)",
	customerId__lbl: "Customer(ID)",
	customerName__lbl: "Customer(Name)",
	customer__lbl: "Customer",
	docPeriod__lbl: "Doc Period",
	dueDate__lbl: "Due Date",
	dueDate__lbl_From: "Due Date(From)",
	dueDate__lbl_To: "Due Date(To)",
	dueInDays__lbl: "Due In Days",
	duePeriod__lbl: "Due period",
	invoiceDate__lbl: "Doc Date",
	invoiceDate__lbl_From: "Doc Date(From)",
	invoiceDate__lbl_To: "Doc Date(To)",
	invoiceId__lbl: "Sales Invoice(ID)",
	invoiceNo__lbl: "Doc No"
});
