Ext.define(Dnet.ns.sd + "SalesInvoiceLineOverview_Ds$Trl", {
	amountLoc__lbl: "Amount Loc",
	amount__lbl: "Amount",
	bpAccountId__lbl: "Business partner account(ID)",
	bpartnerId__lbl: "Customer(ID)",
	bpartnerName__lbl: "Customer(Name)",
	bpartner__lbl: "Customer",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	docDate__lbl: "Doc Date",
	docDate__lbl_From: "Doc Date(From)",
	docDate__lbl_To: "Doc Date(To)",
	docId__lbl: "Invoice(ID)",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	filterPeriod__lbl: "Period",
	netAmountLoc__lbl: "Net Amount Loc",
	netAmount__lbl: "Net Amount",
	netAmount__lbl_From: "Net Amount(From)",
	netAmount__lbl_To: "Net Amount(To)",
	productAccountId__lbl: "Product Account(ID)",
	productId__lbl: "Product(ID)",
	productName__lbl: "Product(Name)",
	product__lbl: "Product",
	quantity__lbl: "Quantity",
	quantity__lbl_From: "Quantity(From)",
	quantity__lbl_To: "Quantity(To)",
	taxAmountLoc__lbl: "Tax Amount Loc",
	taxAmount__lbl: "Tax Amount",
	unitPrice__lbl: "Unit Price",
	unitPrice__lbl_From: "Unit Price(From)",
	unitPrice__lbl_To: "Unit Price(To)",
	uomId__lbl: "Uom(ID)",
	uom__lbl: "Uom"
});
