Ext.define(Dnet.ns.md + "Product_Ds$Trl", {
	attr1__lbl: "Atribut 1",
	attr1id__lbl: "",
	attr1val__lbl: "",
	attr2__lbl: "Atribut 2",
	attr2id__lbl: "",
	attr2val__lbl: "",
	attr3__lbl: "Atribut 3",
	attr3id__lbl: "",
	attr3val__lbl: "",
	attributeSetId__lbl: "Grup atribute(ID)",
	attributeSetName__lbl: "Grup atribute(Den)",
	attributeSet__lbl: "Grup atribute",
	categoryId__lbl: "Categorie(ID)",
	categoryName__lbl: "Categorie(Den)",
	category__lbl: "Categorie",
	dimDepth__lbl: "Lăţime",
	dimHeight__lbl: "Înălţime",
	dimUomId__lbl: "UM dimensiuni(ID)",
	dimUom__lbl: "UM dimensiuni",
	dimWidth__lbl: "Lungime",
	iconLocation__lbl: "",
	iconUrl__lbl: "URL icoană",
	imageLocation__lbl: "",
	imageUrl__lbl: "URL imagine",
	manufacturerId__lbl: "Producător(ID)",
	manufacturerProductNo__lbl: "Cod produc.",
	manufacturer__lbl: "Producător",
	materialId__lbl: "Material(ID)",
	material__lbl: "Material",
	qualityId__lbl: "Calitate(ID)",
	quality__lbl: "Calitate",
	storable__lbl: "Stocabil",
	surfaceId__lbl: "Suprafaţă(ID)",
	surface__lbl: "Suprafaţă",
	uomId__lbl: "UM(ID)",
	uom__lbl: "UM",
	volumeUomId__lbl: "UM Volum(ID)",
	volumeUom__lbl: "UM Volum",
	volume__lbl: "Volum",
	weightUomId__lbl: "UM masă(ID)",
	weightUom__lbl: "UM masă",
	weight__lbl: "Masă"
});
