Ext.define(Dnet.ns.md + "Product_Ds$Trl", {
	attributeSetId__lbl: "Grup atribute(ID)",
	attributeSetName__lbl: "Grup atribute(Den)",
	attributeSet__lbl: "Grup atribute",
	categoryId__lbl: "Categorie(ID)",
	categoryName__lbl: "Categorie(Den)",
	category__lbl: "Categorie",
	dimDepth__lbl: "Lăţime",
	dimHeight__lbl: "Înălţime",
	dimUomId__lbl: "UM dimensiuni(ID)",
	dimUom__lbl: "UM dimensiuni",
	dimWidth__lbl: "Lungime",
	iconLocation__lbl: "",
	iconUrl__lbl: "URL icoană",
	imageLocation__lbl: "",
	imageUrl__lbl: "URL imagine",
	manufacturerId__lbl: "Producător(ID)",
	manufacturerProductNo__lbl: "Cod produc.",
	manufacturer__lbl: "Producător",
	storable__lbl: "Stocabil",
	uomId__lbl: "UM(ID)",
	uom__lbl: "UM",
	volumeUomId__lbl: "UM Volum(ID)",
	volumeUom__lbl: "UM Volum",
	volume__lbl: "Volum",
	weightUomId__lbl: "UM masă(ID)",
	weightUom__lbl: "UM masă",
	weight__lbl: "Masă"
});
