Ext.define(Dnet.ns.md + "Product_Ds$Trl", {
	attr1__lbl: "Attribute 1",
	attr1id__lbl: "",
	attr1val__lbl: "",
	attr2__lbl: "Attribute 2",
	attr2id__lbl: "",
	attr2val__lbl: "",
	attr3__lbl: "Attribute 3",
	attr3id__lbl: "",
	attr3val__lbl: "",
	attributeSetId__lbl: "Attribute Set(ID)",
	attributeSetName__lbl: "Attribute Set(Name)",
	attributeSet__lbl: "Attribute Set",
	categoryId__lbl: "Category(ID)",
	categoryName__lbl: "Category(Name)",
	category__lbl: "Category",
	dimDepth__lbl: "Depth",
	dimHeight__lbl: "Height",
	dimUomId__lbl: "Dim Uom(ID)",
	dimUom__lbl: "Dim Uom",
	dimWidth__lbl: "Width",
	iconLocation__lbl: "",
	iconUrl__lbl: "Icon Url",
	imageLocation__lbl: "",
	imageUrl__lbl: "Image Url",
	manufacturerId__lbl: "Manufacturer(ID)",
	manufacturerProductNo__lbl: "Manufact. prod. code",
	manufacturer__lbl: "Manufacturer",
	storable__lbl: "Storable",
	uomId__lbl: "Default Uom(ID)",
	uom__lbl: "Default Uom",
	volumeUomId__lbl: "Volume Uom(ID)",
	volumeUom__lbl: "Volume Uom",
	volume__lbl: "Volume",
	weightUomId__lbl: "Weight Uom(ID)",
	weightUom__lbl: "Weight Uom",
	weight__lbl: "Weight"
});
