Ext.define(Dnet.ns.tx + "Stock_Ds$Trl", {
	available__lbl: "Available",
	inventoryId__lbl: "Inventory(ID)",
	inventoryName__lbl: "Inventory(Name)",
	inventory__lbl: "Inventory",
	locatorId__lbl: "Location(ID)",
	locatorName__lbl: "Location(Name)",
	locator__lbl: "Location",
	orgId__lbl: "Organization(ID)",
	org__lbl: "Organization",
	productId__lbl: "Product(ID)",
	productName__lbl: "Product(Name)",
	product__lbl: "Product",
	quantity__lbl: "Quantity",
	reserved__lbl: "Reserved",
	uomId__lbl: "UoM(ID)",
	uom__lbl: "UoM",
	valueLoc__lbl: "Value Loc",
	valueRef__lbl: "Value Ref"
});
