Ext.define(Dnet.ns.sd + "PaymentInAmountProposal_Ds$Trl", {
	amountDue_From__lbl: "Sold curent (De la)",
	amountDue_To__lbl: "Sold curent (Pana la)",
	amountDue__lbl: "Sold curent",
	amountInitial_From__lbl: "Sold iniţial (De la)",
	amountInitial_To__lbl: "Sold iniţial (Pana la)",
	amountInitial__lbl: "Sold iniţial",
	amountPayed__lbl: "Achitat",
	bpAccountId__lbl: "Cont terţ(ID)",
	businessPartnerName__lbl: "Plătitor(Den)",
	businessPartner__lbl: "Plătitor",
	companyId__lbl: "Unitate(ID)",
	company__lbl: "Unitate",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	currentPayment__lbl: "Plată curentă",
	dueDate_From__lbl: " (De la)",
	dueDate_To__lbl: " (Pana la)",
	dueDate__lbl: "",
	paymentCurrency__lbl: "Monedă",
	paymentId__lbl: "",
	receivedAmount__lbl: "Sumă plătită",
	remainingAmount__lbl: "Rest",
	unAllocatedAmount__lbl: "Sumă nealocată"
});
