Ext.define(Dnet.ns.sd + "PaymentInAmount_Ds$Trl", {
	amountDue__lbl: "Sold/Rămas",
	amountId__lbl: "Sold(ID)",
	amountInitial_From__lbl: "Sold/Iniţial (De la)",
	amountInitial_To__lbl: "Sold/Iniţial (Pana la)",
	amountInitial__lbl: "Sold/Iniţial",
	amountPayed__lbl: "Sold/Plătit",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	currentPayment__lbl: "Sumă folosită",
	customerAccountId__lbl: "Cont client(ID)",
	customerId__lbl: "Client(ID)",
	customerName__lbl: "Client(Den)",
	customer__lbl: "Client",
	invoiceDocDate__lbl: "Dată factură",
	invoiceId__lbl: "Sales Invoice(ID)",
	invoice__lbl: "Factură",
	paymentAmount__lbl: "Sumă plătită",
	paymentDate__lbl: "Dată plată",
	paymentDocNo__lbl: "Doc plată",
	paymentId__lbl: "Plată(ID)",
	paymentSourceDocNo__lbl: "Doc plată sursă"
});
