Ext.define(Dnet.ns.sd + "Receivable_Ds$Trl", {
	amountPayed_From__lbl: "Valoare (De la)",
	amountPayed_To__lbl: "Valoare (Pana la)",
	amountPayed__lbl: "Valoare",
	amountRemained_From__lbl: "Valoare (De la)",
	amountRemained_To__lbl: "Valoare (Pana la)",
	amountRemained__lbl: "Valoare",
	amount_From__lbl: "Valoare (De la)",
	amount_To__lbl: "Valoare (Pana la)",
	amount__lbl: "Valoare",
	bpAccountId__lbl: "Cont terţ(ID)",
	companyId__lbl: "Unitate(ID)",
	company__lbl: "Unitate",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	customerId__lbl: "Terţ(ID)",
	customerName__lbl: "Terţ(Den)",
	customer__lbl: "Terţ",
	dueDate_From__lbl: " (De la)",
	dueDate_To__lbl: " (Pana la)",
	dueDate__lbl: "",
	dueInDays__lbl: "",
	invoiceDate__lbl: "Dată doc",
	invoiceId__lbl: "Sales Invoice(ID)",
	invoiceNo__lbl: "Nr doc"
});
