Ext.define(Dnet.ns.sd + "SalesOrder_Ds$Trl", {
	amountLoc__lbl: "Total [L]",
	amountRef__lbl: "Total [R]",
	amount__lbl: "Total",
	bpAccountId__lbl: "Terţ(ID)",
	bpartnerId__lbl: "Terţ(ID)",
	bpartnerName__lbl: "Terţ(Den)",
	bpartner__lbl: "Terţ",
	companyId__lbl: "Unitate(ID)",
	company__lbl: "Unitate",
	confirmed__lbl: "Confirmat",
	copyFromId__lbl: "Copiază din doc(ID)",
	copyFrom__lbl: "Copiază din doc",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	docDate_From__lbl: "Dată doc (De la)",
	docDate_To__lbl: "Dată doc (Pana la)",
	docDate__lbl: "Dată doc",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	filterPeriod__lbl: "Perioadă",
	filterProductAccountId__lbl: "Articol(ID)",
	filterProductAccount__lbl: "Articol",
	netAmountLoc__lbl: "Total Net [L]",
	netAmountRef__lbl: "Total Net [R]",
	netAmount__lbl: "Total Net",
	taxAmountLoc__lbl: "Total TVA [L]",
	taxAmountRef__lbl: "Total TVA [R]",
	taxAmount__lbl: "Total TVA",
	xrateLoc__lbl: "Rată de schimb [L]",
	xrateRef__lbl: "Rată de schimb [R]"
});
