Ext.define(Dnet.ns.sd + "SalesInvoiceLineOverview_Ds$Trl", {
	amountLoc__lbl: "Valoare [L]",
	amount__lbl: "Valoare",
	bpAccountId__lbl: "Cont terţ(ID)",
	bpartnerId__lbl: "Client(ID)",
	bpartnerName__lbl: "Client(Den)",
	bpartner__lbl: "Client",
	companyId__lbl: "Unitate(ID)",
	company__lbl: "Unitate",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	docDate_From__lbl: "Dată doc (De la)",
	docDate_To__lbl: "Dată doc (Pana la)",
	docDate__lbl: "Dată doc",
	docId__lbl: "Factură(ID)",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	filterPeriod__lbl: "Perioadă",
	netAmountLoc__lbl: "Valoare netă [L]",
	netAmount_From__lbl: "Valoare netă (De la)",
	netAmount_To__lbl: "Valoare netă (Pana la)",
	netAmount__lbl: "Valoare netă",
	productAccountId__lbl: "Cont articol(ID)",
	productId__lbl: "Articol(ID)",
	productName__lbl: "Articol(Den)",
	product__lbl: "Articol",
	quantity_From__lbl: "Cantitate (De la)",
	quantity_To__lbl: "Cantitate (Pana la)",
	quantity__lbl: "Cantitate",
	taxAmountLoc__lbl: "Valoare taxe [L]",
	taxAmount__lbl: "Valoare taxe",
	unitPrice_From__lbl: "Preţ unitar (De la)",
	unitPrice_To__lbl: "Preţ unitar (Pana la)",
	unitPrice__lbl: "Preţ unitar",
	uomId__lbl: "UM(ID)",
	uom__lbl: "UM"
});
