Ext.define(Dnet.ns.sd + "SalesOrderInfo_Ds$Trl", {
	billToContactId__lbl: "Delegat factură(ID)",
	billToContact__lbl: "Delegat factură",
	billToLocationId__lbl: "Adresă factură(ID)",
	billToLocationRefId__lbl: "Adresă factură",
	billToLocation__lbl: "Adresă factură",
	bpartnerId__lbl: "Terţ(ID)",
	bpartnerRefid__lbl: "Terţ",
	confirmed__lbl: "Confirmat",
	invoiced__lbl: "Facturat",
	paymentMethodId__lbl: "Mod plată(ID)",
	paymentMethodName__lbl: "Mod plată(Den)",
	paymentMethod__lbl: "Mod plată",
	paymentTermId__lbl: "Termen plată(ID)",
	paymentTerm__lbl: "Termen plată",
	shipToContactId__lbl: "Delegat livrare(ID)",
	shipToContact__lbl: "Delegat livrare",
	shipToLocationId__lbl: "Adresă livrare(ID)",
	shipToLocationRefId__lbl: "Adresă livrare",
	shipToLocation__lbl: "Adresă livrare"
});
