Ext.define(Dnet.ns.sc + "Payable_Ds$Trl", {
	amountDue_From__lbl: "Sold curent (De la)",
	amountDue_To__lbl: "Sold curent (Pana la)",
	amountDue__lbl: "Sold curent",
	amountInitial_From__lbl: "Sold iniţial (De la)",
	amountInitial_To__lbl: "Sold iniţial (Pana la)",
	amountInitial__lbl: "Sold iniţial",
	amountPayed_From__lbl: "Achitat (De la)",
	amountPayed_To__lbl: "Achitat (Pana la)",
	amountPayed__lbl: "Achitat",
	companyId__lbl: "Unitate(ID)",
	company__lbl: "Unitate",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	docPeriod__lbl: "Perioadă doc",
	dueDate_From__lbl: " (De la)",
	dueDate_To__lbl: " (Pana la)",
	dueDate__lbl: "",
	dueInDays__lbl: "",
	duePeriod__lbl: "Perioadă scadenţă",
	invoiceDate_From__lbl: "Dată doc (De la)",
	invoiceDate_To__lbl: "Dată doc (Pana la)",
	invoiceDate__lbl: "Dată doc",
	invoiceId__lbl: "Purchase Invoice(ID)",
	invoiceNo__lbl: "Nr doc",
	vendorAccountId__lbl: "Cont furnizor(ID)",
	vendorId__lbl: "Furnizor(ID)",
	vendorName__lbl: "Furnizor(Den)",
	vendor__lbl: "Furnizor"
});
