Ext.define(Dnet.ns.sc + "PaymentOut_Ds$Trl", {
	amountLoc__lbl: "Valoare [L]",
	amountRef__lbl: "Valoare [R]",
	amount_From__lbl: "Valoare (De la)",
	amount_To__lbl: "Valoare (Pana la)",
	amount__lbl: "Valoare",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	direction__lbl: "Sens",
	docDate_From__lbl: "Dată doc. (De la)",
	docDate_To__lbl: "Dată doc. (Pana la)",
	docDate__lbl: "Dată doc.",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	filterPeriod__lbl: "Perioadă",
	finAccountId__lbl: "Cont financiar(ID)",
	finAccount__lbl: "Cont financiar",
	generated__lbl: "Generat",
	posted__lbl: "Inregistrat",
	sourceDocNo__lbl: "Nr doc sursă",
	usage__lbl: "Achită",
	vendorAccountId__lbl: "Cont furnizor(ID)",
	vendorId__lbl: "Furnizor(ID)",
	vendorName__lbl: "Furnizor(Den)",
	vendor__lbl: "Furnizor",
	xrateLoc__lbl: "Rată de schimb [L]",
	xrateRef__lbl: "Rată de schimb [R]"
});
