Ext.define(Dnet.ns.sc + "PaymentOutAmount_Ds$Trl", {
	amountDue__lbl: "Sold/Rămas",
	amountId__lbl: "Sold(ID)",
	amountInitial_From__lbl: "Sold/Iniţial (De la)",
	amountInitial_To__lbl: "Sold/Iniţial (Pana la)",
	amountInitial__lbl: "Sold/Iniţial",
	amountPayed__lbl: "Sold/Plătit",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	currentPayment__lbl: "Sumă folosită",
	invoiceDocDate__lbl: "Dată factură",
	invoiceId__lbl: "Purchase Invoice(ID)",
	invoice__lbl: "Factură",
	paymentAmount__lbl: "Sumă plătită",
	paymentDate__lbl: "Dată plată",
	paymentDocNo__lbl: "Doc plată",
	paymentId__lbl: "Plată(ID)",
	paymentSourceDocNo__lbl: "Doc plată sursă",
	vendorAccountId__lbl: "Cont furnizor(ID)",
	vendorId__lbl: "Furnizor(ID)",
	vendorName__lbl: "Furnizor(Den)",
	vendor__lbl: "Furnizor"
});
