Ext.define(Dnet.ns.sc + "PaymentOut_Ds$Trl", {
	amountLoc__lbl: "Valoare [L]",
	amountRef__lbl: "Valoare [R]",
	amount__lbl: "Valoare",
	bpAccountId__lbl: "De la(ID)",
	bpartnerId__lbl: "Terţ(ID)",
	bpartnerName__lbl: "Terţ(Den)",
	bpartner__lbl: "Terţ",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	confirmed__lbl: "Confirmat",
	currencyId__lbl: "Monedă(ID)",
	currency__lbl: "Monedă",
	docDate_From__lbl: "Dată doc. (De la)",
	docDate_To__lbl: "Dată doc. (Pana la)",
	docDate__lbl: "Dată doc.",
	docNo__lbl: "Nr doc",
	docTypeId__lbl: "Tip doc(ID)",
	docType__lbl: "Tip doc",
	generated__lbl: "Generat",
	posted__lbl: "Inregistrat",
	sourceDocNo__lbl: "Nr doc sursa",
	xrateLoc__lbl: "Rată de schimb [L]",
	xrateRef__lbl: "Rată de schimb [R]"
});
