Ext.define(Dnet.ns.sd + "SalesInvoice_Ui$Trl" , {
	/* view */
	atchList__ttl: "Ataşamente",
	infoEdit__ttl: "Info factură",
	lineFilter__ttl: "Filtru",
	lineTaxList__ttl: "Taxe linie factură",
	linesPanel__ttl: "Linii factură",
	taxList__ttl: "Taxe",
	wdwCopyLines__ttl: "Copiază linii din factură",
	wdwCreate__ttl: "Factură nouă",
	/* menu */
	tlbAtchList__ttl: "Ataşamente",
	tlbInfoEdit__ttl: "Info factură",
	tlbInvEdit__ttl: "Factură client",
	tlbInvList__ttl: "Facturi client",
	tlbLineEdit__ttl: "Linie factură",
	tlbLineList__ttl: "Linii factură",
	tlbLineTaxList__ttl: "Taxe linie",
	tlbTaxList__ttl: "Taxe",
	/* button */
	btnConfirm__lbl: "Confirmă",
	btnConfirm__tlp: "Confirmă factură",
	btnCreateCancel__lbl: "Renunţă",
	btnCreateCancel__tlp: "",
	btnCreateContinue__lbl: "Continuă",
	btnCreateContinue__tlp: "",
	btnDoCopyLines__lbl: "Execută",
	btnDoCopyLines__tlp: "",
	btnPost__lbl: "Inregistrează",
	btnPost__tlp: "Inregistrează factură in contabilitate",
	btnShowBpAccount__lbl: "Cont client",
	btnShowBpAccount__tlp: "Arată cont client",
	btnShowCopyLines__lbl: "Copiază linii",
	btnShowCopyLines__tlp: "Copiază linii din factură",
	btnShowOrder__lbl: "Arată comandă",
	btnShowOrder__tlp: "Arată comanda client asociată acestei facturi.",
	btnUnConfirm__lbl: "De-Confirmă",
	btnUnConfirm__tlp: "De-confirmă factură",
	btnUnPost__lbl: "De-Inregistrează",
	btnUnPost__tlp: "De-Inregistrează factură din contabilitate",
	
	title: "Facturi client"
});
