Ext.define(Dnet.ns.sd + "SalesOrder_Ui$Trl" , {
	/* view */
	atchList__ttl: "Ataşamente",
	infoEdit__ttl: "Info comandă",
	lineFilter__ttl: "Filtru",
	lineTaxList__ttl: "Taxe linie comandă",
	linesPanel__ttl: "Linii comandă",
	taxList__ttl: "Taxe",
	wdwCopyLines__ttl: "Copiază linii din comandă",
	wdwCreate__ttl: "Comandă nouă",
	wdwGenInvoice__ttl: "Generează factură",
	/* menu */
	tlbAtchList__ttl: "Ataşamente",
	tlbInfoEdit__ttl: "Info comandă",
	tlbLineEdit__ttl: "Linie comandă",
	tlbLineList__ttl: "Linii comandă",
	tlbLineTaxList__ttl: "Taxe linie",
	tlbOrdEdit__ttl: "Comandă client",
	tlbOrdList__ttl: "Comenzi client",
	tlbTaxList__ttl: "Taxe",
	/* button */
	btnConfirm__lbl: "Confirmă",
	btnConfirm__tlp: "Confirma comandă",
	btnCreateCancel__lbl: "Renunţă",
	btnCreateCancel__tlp: "",
	btnCreateContinue__lbl: "Continuă",
	btnCreateContinue__tlp: "",
	btnCreateInvoice__lbl: "Gen. factură",
	btnCreateInvoice__tlp: "Generează factură",
	btnCreateInvoiceOk__lbl: "OK",
	btnCreateInvoiceOk__tlp: "Generează factură",
	btnDoCopyLines__lbl: "Execută",
	btnDoCopyLines__tlp: "",
	btnShowBpAccount__lbl: "Cont client",
	btnShowBpAccount__tlp: "Arată cont client",
	btnShowCopyLines__lbl: "Copiază linii",
	btnShowCopyLines__tlp: "Copiază linii din comandă",
	btnShowInvoice__lbl: "Arată factură",
	btnShowInvoice__tlp: "Arată factură",
	btnUnConfirm__lbl: "De-Confirma",
	btnUnConfirm__tlp: "De-confirmă comandă",
	
	title: "Comenzi client"
});
