Ext.define(Dnet.ns.sd + "SalesOrder_Ui$Trl" , {
	/* view */
	atchList__ttl: "Atasamente",
	infoEdit__ttl: "Info comanda",
	lineFilter__ttl: "Filtru",
	lineTaxList__ttl: "Taxe linie comanda",
	linesPanel__ttl: "Linii comanda",
	taxList__ttl: "Taxe",
	wdwCopyLines__ttl: "Copiaza linii din comanda",
	wdwCreate__ttl: "Comanda noua",
	wdwGenInvoice__ttl: "Genereaza factura",
	/* menu */
	tlbAtchList__ttl: "Atasamente",
	tlbInfoEdit__ttl: "Info comanda",
	tlbLineEdit__ttl: "Linie comanda",
	tlbLineList__ttl: "Linii comanda",
	tlbLineTaxList__ttl: "Taxe linie",
	tlbOrdEdit__ttl: "Comanda client",
	tlbOrdList__ttl: "Comenzi client",
	tlbTaxList__ttl: "Taxe",
	/* button */
	btnConfirm__lbl: "Confirma",
	btnConfirm__tlp: "Confirma factura",
	btnCreateCancel__lbl: "Renunta",
	btnCreateCancel__tlp: "",
	btnCreateContinue__lbl: "Continua",
	btnCreateContinue__tlp: "",
	btnCreateInvoice__lbl: "Gen. factura",
	btnCreateInvoice__tlp: "Genereaza factura",
	btnCreateInvoiceOk__lbl: "OK",
	btnCreateInvoiceOk__tlp: "Genereaza factura",
	btnDoCopyLines__lbl: "Executa",
	btnDoCopyLines__tlp: "",
	btnShowBpAccount__lbl: "Cont client",
	btnShowBpAccount__tlp: "Arata cont client",
	btnShowCopyLines__lbl: "Copiaza linii",
	btnShowCopyLines__tlp: "Copiaza linii din comanda",
	btnShowInvoice__lbl: "Arata factura",
	btnShowInvoice__tlp: "Arata factura",
	btnUnConfirm__lbl: "De-Confirma",
	btnUnConfirm__tlp: "De-confirma factura",
	
	title: "Comenzi client"
});
