Ext.define(Dnet.ns.sc + "Payable_Ds$Trl", {
	amountPayed__lbl: "Amount Payed",
	amountPayed__lbl_From: "Amount Payed(From)",
	amountPayed__lbl_To: "Amount Payed(To)",
	amountRemained__lbl: "Amount Remained",
	amountRemained__lbl_From: "Amount Remained(From)",
	amountRemained__lbl_To: "Amount Remained(To)",
	amount__lbl: "Amount",
	amount__lbl_From: "Amount(From)",
	amount__lbl_To: "Amount(To)",
	bpAccountId__lbl: "Bp Account(ID)",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	dueDate__lbl: "Due Date",
	dueDate__lbl_From: "Due Date(From)",
	dueDate__lbl_To: "Due Date(To)",
	dueInDays__lbl: "Due In Days",
	invoiceDate__lbl: "Doc Date",
	invoiceId__lbl: "Purchase Invoice(ID)",
	invoiceNo__lbl: "Doc No",
	vendorId__lbl: "Business partner(ID)",
	vendorName__lbl: "Business partner(Name)",
	vendor__lbl: "Business partner"
});
