Ext.define(Dnet.ns.sc + "Payable_Ds$Trl", {
	amountDue__lbl: "Due amount",
	amountDue__lbl_From: "Due amount(From)",
	amountDue__lbl_To: "Due amount(To)",
	amountInitial__lbl: "Initial amount",
	amountInitial__lbl_From: "Initial amount(From)",
	amountInitial__lbl_To: "Initial amount(To)",
	amountPayed__lbl: "Payed amount",
	amountPayed__lbl_From: "Payed amount(From)",
	amountPayed__lbl_To: "Payed amount(To)",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	docPeriod__lbl: "Doc Period",
	dueDate__lbl: "Due Date",
	dueDate__lbl_From: "Due Date(From)",
	dueDate__lbl_To: "Due Date(To)",
	dueInDays__lbl: "Due In Days",
	duePeriod__lbl: "Due period",
	invoiceDate__lbl: "Doc Date",
	invoiceDate__lbl_From: "Doc Date(From)",
	invoiceDate__lbl_To: "Doc Date(To)",
	invoiceId__lbl: "Purchase Invoice(ID)",
	invoiceNo__lbl: "Doc No",
	vendorAccountId__lbl: "Vendor account(ID)",
	vendorId__lbl: "Vendor(ID)",
	vendorName__lbl: "Vendor(Name)",
	vendor__lbl: "Vendor"
});
