Ext.define(Dnet.ns.sc + "PaymentOutAmountProposal_Ds$Trl", {
	amountDue__lbl: "Due amount",
	amountDue__lbl_From: "Due amount(From)",
	amountDue__lbl_To: "Due amount(To)",
	amountInitial__lbl: "Initial amount",
	amountInitial__lbl_From: "Initial amount(From)",
	amountInitial__lbl_To: "Initial amount(To)",
	amountPayed__lbl: "Payed amount",
	businessPartnerName__lbl: "Payed to(Name)",
	businessPartner__lbl: "Payed to",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	currentPayment__lbl: "Current payment",
	dueDate__lbl: "Due Date",
	dueDate__lbl_From: "Due Date(From)",
	dueDate__lbl_To: "Due Date(To)",
	paymentCurrency__lbl: "Currency",
	paymentId__lbl: "",
	receivedAmount__lbl: "Received amount",
	remainingAmount__lbl: "Remaining",
	unAllocatedAmount__lbl: "Unused amount",
	vendorAccountId__lbl: "Vendor account(ID)"
});
