Ext.define(Dnet.ns.sc + "PaymentOutAmount_Ds$Trl", {
	amountDue__lbl: "Due/Remained",
	amountId__lbl: "Amount Owed(ID)",
	amountInitial__lbl: "Due/Initial",
	amountInitial__lbl_From: "Due/Initial(From)",
	amountInitial__lbl_To: "Due/Initial(To)",
	amountPayed__lbl: "Due/Payed",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	currentPayment__lbl: "Used amount",
	invoiceDocDate__lbl: "Invoice date",
	invoiceId__lbl: "Purchase Invoice(ID)",
	invoice__lbl: "Invoice",
	paymentAmount__lbl: "Payed amount",
	paymentDate__lbl: "Payment date",
	paymentDocNo__lbl: "Payment doc",
	paymentId__lbl: "Payment(ID)",
	paymentSourceDocNo__lbl: "Payment src doc",
	vendorAccountId__lbl: "Vendor account(ID)",
	vendorId__lbl: "Vendor(ID)",
	vendorName__lbl: "Vendor(Name)",
	vendor__lbl: "Vendor"
});
