Ext.define(Dnet.ns.sc + "PaymentOut_Ds$Trl", {
	amountLoc__lbl: "Amount Loc",
	amountRef__lbl: "Amount Ref",
	amount__lbl: "Amount",
	amount__lbl_From: "Amount(From)",
	amount__lbl_To: "Amount(To)",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	confirmed__lbl: "Confirmed",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	direction__lbl: "Direction",
	docDate__lbl: "Doc Date",
	docDate__lbl_From: "Doc Date(From)",
	docDate__lbl_To: "Doc Date(To)",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	filterPeriod__lbl: "Period",
	finAccountId__lbl: "Fin Account(ID)",
	finAccount__lbl: "Fin Account",
	generated__lbl: "Generated",
	posted__lbl: "Posted",
	sourceDocNo__lbl: "Source Doc No",
	usage__lbl: "Pay for",
	vendorAccountId__lbl: "Vendor account(ID)",
	vendorId__lbl: "Vendor(ID)",
	vendorName__lbl: "Vendor(Name)",
	vendor__lbl: "Vendor",
	xrateLoc__lbl: "Exchange rate [L]",
	xrateRef__lbl: "Exchange rate [R]"
});
