Ext.define(Dnet.ns.sc + "PurchaseOrder_Ds$Trl", {
	amountLoc__lbl: "Amount [L]",
	amountRef__lbl: "Amount [R]",
	amount__lbl: "Amount",
	bpAccountId__lbl: "Business partner account(ID)",
	bpartnerId__lbl: "Business partner(ID)",
	bpartnerName__lbl: "Business partner(Name)",
	bpartner__lbl: "Business partner",
	companyId__lbl: "Company(ID)",
	company__lbl: "Company",
	confirmed__lbl: "Confirmed",
	copyFromId__lbl: "Copy from (ID)",
	copyFrom__lbl: "Copy from ",
	currencyId__lbl: "Currency(ID)",
	currency__lbl: "Currency",
	docDate__lbl: "Doc Date",
	docDate__lbl_From: "Doc Date(From)",
	docDate__lbl_To: "Doc Date(To)",
	docNo__lbl: "Doc No",
	docTypeId__lbl: "Doc Type(ID)",
	docType__lbl: "Doc Type",
	filterPeriod__lbl: "Period",
	filterProductAccountId__lbl: "Product(ID)",
	filterProductAccount__lbl: "Product",
	netAmountLoc__lbl: "Net amount [L]",
	netAmountRef__lbl: "Net amount [R]",
	netAmount__lbl: "Net Amount",
	paymentMethodId__lbl: "Payment Method(ID)",
	paymentMethodName__lbl: "Payment Method(Name)",
	paymentMethod__lbl: "Payment Method",
	paymentTermId__lbl: "Payment Term(ID)",
	paymentTerm__lbl: "Payment Term",
	taxAmountLoc__lbl: "Tax amount [L]",
	taxAmountRef__lbl: "Tax amount [R]",
	taxAmount__lbl: "Tax Amount",
	xrateLoc__lbl: "Exchange rate [L]",
	xrateRef__lbl: "Exchange rate [R]"
});
