Ext.define(Dnet.ns.sd + "SalesOrder_Ui$Trl" , {
	/* view */
	atchList__ttl: "Attachments",
	infoEdit__ttl: "Order info",
	lineFilter__ttl: "Filter",
	lineTaxList__ttl: "Item taxes",
	linesPanel__ttl: "Order lines",
	taxList__ttl: "Taxes",
	wdwCopyLines__ttl: "Copy lines from order",
	wdwCreate__ttl: "Create order",
	wdwGenInvoice__ttl: "Generate invoice",
	/* menu */
	tlbAtchList__ttl: "Attachments",
	tlbInfoEdit__ttl: "Order info",
	tlbLineEdit__ttl: "Order line",
	tlbLineList__ttl: "Order lines",
	tlbLineTaxList__ttl: "Line tax",
	tlbOrdEdit__ttl: "Sales order",
	tlbOrdList__ttl: "Sales orders",
	tlbTaxList__ttl: "Taxes",
	/* button */
	btnConfirm__lbl: "Confirm",
	btnConfirm__tlp: "Confirm order.",
	btnCreateCancel__lbl: "Cancel",
	btnCreateCancel__tlp: "",
	btnCreateContinue__lbl: "Continue",
	btnCreateContinue__tlp: "",
	btnCreateInvoice__lbl: "Gen. Invoice",
	btnCreateInvoice__tlp: "Generate Invoice",
	btnCreateInvoiceOk__lbl: "OK",
	btnCreateInvoiceOk__tlp: "Generate Invoice",
	btnDoCopyLines__lbl: "Execute",
	btnDoCopyLines__tlp: "",
	btnShowBpAccount__lbl: "Customer account",
	btnShowBpAccount__tlp: "Show customer account",
	btnShowCopyLines__lbl: "Copy lines",
	btnShowCopyLines__tlp: "Copy lines from order",
	btnShowInvoice__lbl: "Show invoice",
	btnShowInvoice__tlp: "Show invoice",
	btnUnConfirm__lbl: "Un-Confirm",
	btnUnConfirm__tlp: "Un-Confirm order.",
	
	title: "Sales orders"
});
